### ISSUE TITLE
Where are Domain Events?

### ISSUE THREAD

**Issue by TM-Atharva** [Ridikk12/ModularMonolith#6]
Hi @Ridikk12  - I recently found your great series of articles on Modular Monolith and found your repo from there. I must say that you have very good explanation skill from basic to pro level.

After your 6th article there is not further articles and code implementation so from where can I find out further stuff??

Thanks in Advance!

**Comment by Ridikk12** [comment]
Hi,
Thanks for your comment. I much appreciate it. 

The article you are asking for is on my TODO list, and I will deliver it as soon as possible. It's tough to say when it will be, as I'm pretty occupied right now.

**Comment by TM-Atharva** [comment]
Hope you make it soon!!

We are working on modular monolith and planning to create full fledge architecture around that. Could you guide me out how to implement outbox/inbox pattern and use user context in cross modules.

Thanks in Advance!!
