### ISSUE TITLE
Please suggest any reference for below topics to take this further.

### ISSUE THREAD

**Issue by TM-Atharva** [Ridikk12/ModularMonolith#7]
- Domain events.
- Asynchronous communication.
- OutBox improvements.
- Unit/Integration tests.
- Storing configuration.
- The database approaches (multiple data sources).
- Preparing for Microservices (Replacing MediatR by RabbitMq).
- Migrate to Microservices.

**Comment by patrikduch** [comment]
Replacing MediatR by RabbitMq is not a good idea, but using RabbitMq for asynchronous communication can work.

**Unit and Integration tests**
https://github.com/patrikduch/netcore-microservices/tree/master/src/services/Product/Product.Tests

**.NET Microservices example**
https://github.com/patrikduch/netcore-microservices

**Comment by TM-Atharva** [comment]
Hey thanks for reply, These are the topics which are not pending for @Ridikk12  to write over medium. I was looking forward to complete this code with all the above features.

**Comment by Ridikk12** [comment]
Hi @TM-Atharva, 
I appreciate your interest. 
I'm unable to commit to any dates. Still, I recently got back to this side project and am working on improvements - I would expect that code will appear in the repository before articles on Medium.

Regarding the references: 

- Async Communication - https://masstransit.io/
- Integration Tests - https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-7.0
- Unit Tests - https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test 
 https://github.com/AutoFixture/AutoFixture
 https://fluentassertions.com/introduction
 https://github.com/moq/moq
